permalink: /blog/:year/:month/:day/:title
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - package.json.ls
  - package.json
  - README.md
  - node_modules
  - scripts
safe: true
lsi: false
title: 'Grasp - JavaScript structural search, replace, and refactor'
version: '0.2.1'
